### ISSUE TITLE
"Not translated" / "Nicht übersetzt": How can I help?

### ISSUE THREAD

**Issue by genodeftest** [Jugendhackt/HowToPGP#21]
On quite many combinations of OS+Mail Client+… I get this message:

```
Not translated

This part of the instruction is not yet translated or does not exist. You can help building the website by participating on Github.
```

But I don't know what to do exactly. It would be very good to have some kind of TODO-list for this project so that volunteers can contribute. What do you need?

**Comment by two-heart** [comment]
Thank you for your question. A very good idea. I wrote a [CONTRIBUTING.md file](https://github.com/Jugendhackt/HowToPGP/blob/master/CONTRIBUTING.md). I hope it helps.

**Comment by corvusmo** [comment]
The problem is, that at the moment this "not translated" thing isn't very flexible. This comment has to be added manually and does not consider the current language (it's included in all languages at a given position). It would be better to check if a translated file exists and include the not_translated.html if it doesn't.
Currently there is only one file untranslated (en/mailvelope_create_keys.html), plus maybe parts missing in all languages.
